management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.46.57.237:8848
  data:
    redis:
      repositories:
        #forbid redis to scan repositories
        enabled: false
  # redis:
      host: 127.0.0.1
      database: 0
      password:
  datasource:
    #JDBC drivers
    driver-class-name: com.mysql.cj.jdbc.Driver
    #database url
    url: jdbc:mysql://120.46.57.237:3306/aftersale?serverTimezone=Asia/Shanghai
    #database username and password
    username: demouser
    password: 123456
    #database connection pool
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
  jackson:
    time-zone: GMT+8
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8085
  tomcat:
    threads:
      max: 200
      min-spare: 100

oomall:
  core:
    page-size:
      max: 1000
      default: 10
  aftersale:
    timeout: 3600